//@version=5
indicator(title = "ADX Di+ Di- [@Ultr]", shorttitle = "ADX +Di- [@Ultr]", overlay = false, format = format.price, precision = 2, timeframe = '')


/// ────────────
/// ─── +Di- ───
/// ─── Colors ─

/// ─── Standard ──
	//  color.aqua								= #00BCD4
	//  color.blue								= #2196F3
	//  color.teal								= #00897B
	//  color.green								= #4CAF50
	//  color.olive								= #808000
	//  color.lime								= #00E676
	//  color.yellow							= #FFEB3B
	//  color.orange							= #FF9800
	//  color.maroon							= #880E4F
	//  color.red								= #FF5252
	//  color.fuchsia							= #E040FB
	//  color.purple							= #9C27B0
	//  color.navy								= #311B92
	//  color.black								= #363A45
	//  color.gray								= #787B86
	//  color.silver							= #B2B5BE
	//  color.white								= #FFFFFF

/// ─── Ameritrade ───
	//  AmeTrWhite								= #FFFFFF								// AmeritradeWhite
	//  AmeTrGrayPlatinum						= #F7F7F7								// AmeritradeGrayPlatinum
AmeTrGrayNickel								= #F1F1F1								// AmeritradeGrayNickel
	//  AmeTrGrayNickelDark20					= #C0C0C0								// AmeritradeGrayNickelDark20
	//  AmeTrGrayAluminum						= #E6E7E9								// AmeritradeGrayAluminum
	//  AmeTrGrayAsh							= #D8D8D8								// AmeritradeGrayAsh
	//  AmeTrGrayStone							= #999999								// AmeritradeGrayStone
	//  AmeTrGrayIron							= #666666								// AmeritradeGrayIron
	//  AmeTrGrayCharcoal						= #333333								// AmeritradeGrayCharcoal
	//  AmeTrBlack								= #000000								// AmeritradeBlack
	//  AmeTrGreenCabbage						= #EBF6E9								// AmeritradeGreenCabbage
	//  AmeTrGreenVerdeLight70					= #B4D6B2								// AmeritradeGreenVerdeLight70
	//  AmeTrGreenVerdeLight50					= #83BC7F								// AmeritradeGreenVerdeLight50
	//  AmeTrGreenVerdeNat						= #40a829								// AmeritradeGreenVerdeNat
	//  AmeTrGreenVerdeLight20					= #399333								// AmeritradeGreenVerdeLight20
	//  AmeTrGreenVerde							= #087900								// AmeritradeGreenVerde
	//  AmeTrGreenVerdeDark20					= #066000								// AmeritradeGreenVerdeDark20
	//  AmeTrGreenMoss							= #BEE7D3								// AmeritradeGreenMoss
	//  AmeTrGreenMint							= #6DC4BC								// AmeritradeGreenMint
	//  AmeTrGreenPine							= #38635A								// AmeritradeGreenPine
	//  AmeTrRedRose							= #FAD1CF								// AmeritradeRedRose
	//  AmeTrRedRojaLight50						= #E08988								// AmeritradeRedRojaLight50
	//  AmeTrRedRojaLight20						= #CD4241								// AmeritradeRedRojaLight20
	//  AmeTrRedRoja							= #C11312								// AmeritradeRedRoja
	//  AmeTrRedRojaDark20						= #940F0E								// AmeritradeRedRojaDark20
	//  AmeTrorangePeach						= #FCE7CA								// AmeritradeorangePeach
	//  AmeTrorangeCarrot						= #ED8902								// AmeritradeorangeCarrot
	//  AmeTrorangeYam							= #BD5310								// AmeritradeorangeYam
	//  AmeTrblueFrost							= #E1EEF9								// AmeritradeblueFrost
	//  AmeTrblueLagoon							= #316486								// AmeritradeblueLagoon
	//  AmeTrblueNavy							= #2A5673								// AmeritradeblueNavy
	//  AmeTrblueNcean							= #64A1C6								// AmeritradeblueNcean
	//  AmeTrpurpleEggPlant						= #732181								// AmeritradepurpleEggPlant

/// ─── Axi ───
	//  AxiPrimary								= #fc404d								// AxiPrimary
	//  AxiSecondary							= #282424								// AxiSecondary
	//  AxiAccent								= #61ce70								// AxiAccent
	//  Axi7a46f22								= #d11c36								// Axi7a46f22
	//  Axi1519066c								= #fc404d								// Axi1519066c
	//  Axi3d4fa1a1								= #f0ebe3								// Axi3d4fa1a1
	//  Axi638b46c1								= #fcd758								// Axi638b46c1
	//  Axid07bac9								= #f9b4a8								// Axid07bac9
	//  Axie63a114								= #2c4d5a								// Axie63a114
	//  Axi8bf0845								= #a4d866								// Axi8bf0845
	//  Axi75c6da1								= #282424								// Axi75c6da1
	//  Axi378280f								= #45c2c7								// Axi378280f
	//  Axi4de92c5								= #6caddf								// Axi4de92c5
Axi413dab8			    					= #00275d					            // Axi413dab8
	//  Axib3fab89								= #55165c								// Axib3fab89
	//  Axi548138f								= #45c2c7								// Axi548138f
	//  Axi5ed9920								= #ea1616								// Axi5ed9920
	//  Axi70f7335								= #dd0606								// Axi70f7335

/// ─── GrayScale ───
	//  GraySFocus								= #2d7aed								// GrayScaleFocus
	//  GraySWhite								= #fff									// GrayScaleWhite
	//  GraySBlack								= #000									// GrayScaleBlack
	//  GraySPrimaryBlackberry					= #2e234b								// GrayScalePrimaryBlackberry
	//  GraySPrimaryBlackberry40				= rgba(46, 35, 75, .4))			    	// GrayScalePrimaryBlackberry40
	//  GraySPrimaryBlackberry65				= rgba(46, 35, 75, .65))				// GrayScalePrimaryBlackberry65
	//  GraySPrimaryCoral						= #ffb198								// GrayScalePrimaryCoral
	//  GraySSecondaryForestGreen				= #244024								// GrayScaleSecondaryForestGreen
	//  GraySSecondaryKeyLime					= #b5ce6f								// GrayScaleSecondaryKeyLime
	//  GraySSecondaryLavender					= #c5bfe4								// GrayScaleSecondaryLavender
	//  GraySSecondaryLavender40				= rgba(197, 191, 228, .4))				// GrayScaleSecondaryLavender40
	//  GraySsecondaryLavender60				= rgba(197, 191, 228, .6))				// GrayScalesecondaryLavender60
	//  GrayShoverWhite							= #c0bdc9								// GrayScalehoverWhite
	//  GrayShoverBlackberry					= #42326b								// GrayScalehoverBlackberry
	//  GraySdisabledBlackberry					= #4d4466								// GrayScaledisabledBlackberry
	//  GraySactiveBlackberry					= #4d4466								// GrayScaleactiveBlackberry
	//  GrayShoverCcoral						= #ffcdbd								// GrayScalehoverCcoral
	//  GraySactiveCcoral						= #ff9e80								// GrayScaleactiveCcoral
	//  GrayShoverGray							= #827b93								// GrayScalehoverGray
	//  GrayShoverGray2							= #6d6581								// GrayScalehoverGray2
	//  GraySgrayCharcoal						= #282525								// GrayScalegrayCharcoal
	//  GraySgrayCharcoal70						= rgba(40, 37, 37, .7))			    	// GrayScalegrayCharcoal70
	//  GraySgrayCharcoal80						= rgba(40, 37, 37, .8))			    	// GrayScalegrayCharcoal80
	//  GraySgrayLight							= #f5f5f5								// GrayScalegrayLight
	//  GraySgrayMedium							= #eee									// GrayScalegrayMedium
	//  GraySgray70								= #696666								// GrayScalegray70
	//  GraySgrayDark							= #c1c1c1								// GrayScalegrayDark
GraySwebSeasalt			    				= #fafafc								// GrayScalewebSeasalt
	//  GraySwebDivider							= #e9e7f1								// GrayScalewebDivider
	//  GraySwebBackground						= #f3f2fa								// GrayScalewebBackground
	//  GraySwebSecondaryText					= #77708a								// GrayScalewebSecondaryText
	//  GraySwebStroke							= #d3ceeb								// GrayScalewebStroke
	//  GraySwebErrors							= #e00000								// GrayScalewebErrors
	//  GraySwebService							= #2d7aed								// GrayScalewebService

/// ─── Interactive ───
	//  IntAcPrimary3							= hsla(355, 85%, 46%, 0.03)		    	// InteractivePrimary3
	//  IntAcPrimary5							= hsla(355, 85%, 46%, 0.05)		    	// InteractivePrimary5
	//  IntAcPrimary10							= hsla(355, 85%, 46%, 0.10)		    	// InteractivePrimary10
	//  IntAcPrimary20							= hsla(355, 85%, 46%, 0.20)		    	// InteractivePrimary20
	//  IntAcPrimary30							= hsla(355, 85%, 46%, 0.30)		    	// InteractivePrimary30
	//  IntAcPrimary40							= hsla(355, 85%, 46%, 0.40)		    	// InteractivePrimary40
	//  IntAcPrimary50							= hsla(355, 85%, 46%, 0.50)		    	// InteractivePrimary50
	//  IntAcPrimary60							= hsla(355, 85%, 46%, 0.60)		    	// InteractivePrimary60
	//  IntAcPrimary70							= hsla(355, 85%, 46%, 0.70)		    	// InteractivePrimary70
	//  IntAcPrimary80							= hsla(355, 85%, 46%, 0.80)		    	// InteractivePrimary80
	//  IntAcPrimary90							= hsla(355, 85%, 46%, 0.90)		    	// InteractivePrimary90
	//  IntAcPrimary							= hsla(355, 85%, 46%, 1.0)				// InteractivePrimary
	//  IntAcPrimaryDark10						= hsla(355, 85%, 41%, 1.0)				// InteractivePrimaryDark10
	//  IntAcPrimaryDark20						= hsla(355, 85%, 36%, 1.0)				// InteractivePrimaryDark20
	//  IntAcPrimaryDark30						= hsla(355, 85%, 31%, 1.0)				// InteractivePrimaryDark30
	//  IntAcPrimaryDark40						= hsla(355, 85%, 26%, 1.0)				// InteractivePrimaryDark40
	//  IntAcPrimaryDark50						= hsla(355, 85%, 21%, 1.0)				// InteractivePrimaryDark50
	//  IntAcSecondary3							= hsla(0, 0%, 13%, 0.03)				// InteractiveSecondary3
	//  IntAcSecondary5							= hsla(0, 0%, 13%, 0.05)				// InteractiveSecondary5
	//  IntAcSecondary10						= hsla(0, 0%, 13%, 0.10)				// InteractiveSecondary10
	//  IntAcSecondary20						= hsla(0, 0%, 13%, 0.20)				// InteractiveSecondary20
	//  IntAcSecondary30						= hsla(0, 0%, 13%, 0.30)				// InteractiveSecondary30
	//  IntAcSecondary40						= hsla(0, 0%, 13%, 0.40)				// InteractiveSecondary40
	//  IntAcSecondary50						= hsla(0, 0%, 13%, 0.50)				// InteractiveSecondary50
	//  IntAcSecondary60						= hsla(0, 0%, 13%, 0.60)				// InteractiveSecondary60
	//  IntAcSecondary70						= hsla(0, 0%, 13%, 0.70)				// InteractiveSecondary70
	//  IntAcSecondary80						= hsla(0, 0%, 13%, 0.80)				// InteractiveSecondary80
	//  IntAcSecondary90						= hsla(0, 0%, 13%, 0.90)				// InteractiveSecondary90
	//  IntAcSecondary							= hsla(0, 0%, 13%, 1.0)			    	// InteractiveSecondary
	//  IntAcSecondaryDark10					= hsla(0, 0%, 10%, 1.0)			    	// InteractiveSecondaryDark10
	//  IntAcSecondaryDark20					= hsla(0, 0%, 7%, 1.0)					// InteractiveSecondaryDark20
	//  IntAcSecondaryDark30					= hsla(0, 0%, 4%, 1.0)					// InteractiveSecondaryDark30
	//  IntAcSecondaryDark40					= hsla(0, 0%, 1%, 1.0)					// InteractiveSecondaryDark40
	//  IntAcSecondaryDark50					= hsla(0, 0%, 0%, 1.0)					// InteractiveSecondaryDark50
	//  IntAcTertiary3							= hsla(202, 76%, 19%, 0.03)		    	// InteractiveTertiary3
	//  IntAcTertiary5							= hsla(202, 76%, 19%, 0.05)		    	// InteractiveTertiary5
	//  IntAcTertiary10							= hsla(202, 76%, 19%, 0.10)		    	// InteractiveTertiary10
	//  IntAcTertiary20							= hsla(202, 76%, 19%, 0.20)		    	// InteractiveTertiary20
	//  IntAcTertiary30							= hsla(202, 76%, 19%, 0.30)		    	// InteractiveTertiary30
	//  IntAcTertiary40							= hsla(202, 76%, 19%, 0.40)		    	// InteractiveTertiary40
	//  IntAcTertiary50							= hsla(202, 76%, 19%, 0.50)		    	// InteractiveTertiary50
	//  IntAcTertiary60							= hsla(202, 76%, 19%, 0.60)		    	// InteractiveTertiary60
	//  IntAcTertiary70							= hsla(202, 76%, 19%, 0.70)		    	// InteractiveTertiary70
	//  IntAcTertiary80							= hsla(202, 76%, 19%, 0.80)		    	// InteractiveTertiary80
	//  IntAcTertiary90							= hsla(202, 76%, 19%, 0.90)		    	// InteractiveTertiary90
	//  IntAcTertiary							= hsla(202, 76%, 19%, 1.0)				// InteractiveTertiary
	//  IntAcTertiaryDark10						= hsla(202, 76%, 14%, 1.0)				// InteractiveTertiaryDark10
	//  IntAcTertiaryDark20						= hsla(202, 76%, 9%, 1.0)				// InteractiveTertiaryDark20
	//  IntAcTertiaryDark30						= hsla(202, 76%, 4%, 1.0)				// InteractiveTertiaryDark30
	//  IntAcTertiaryDark40						= hsla(202, 76%, 0%, 1.0)				// InteractiveTertiaryDark40

/// ─── Visa ───
	// 	VisPrimary								= #1434CB								// VisaBrandPrimary
	// 	VisPrimaryLight							= #3B57DE								// VisaBrandPrimaryLight
	// 	VisPrimaryDark							= #021E4C								// VisaBrandPrimaryDark
	// 	VisSecondary							= #FCC015								// VisaBrandSecondary
	// 	VisSecondaryLight						= #FFD700								// VisaBrandSecondaryLight
	// 	VisSecondaryDark						= #F7B600								// VisaBrandSecondaryDark
	// 	VisTertiary7							= #2C2C2C								// VisaBrandTertiary7
	// 	VisTertiary6							= #5C5C5C								// VisaBrandTertiary6
	// 	VisTertiary5							= #979797								// VisaBrandTertiary5
	// 	VisTertiary4							= #B9B9B9								// VisaBrandTertiary4
	// 	VisTertiary3							= #DEDEDE								// VisaBrandTertiary3
	// 	VisTertiary2							= #EEEEEE								// VisaBrandTertiary2
	// 	VisTertiary1							= #F7F7F7								// VisaBrandTertiary1

/// ─── Latam ───
	// 	LatRedBackground						= rgb(232, 17, 75)						// Latam Red Background

/// ─── Arbe Robotics ───
ARoPrimary									= #0035FF								// ArbePrimary
	// 	ARoPrimaryLight							= #0640FF								// ArbePrimaryLight
ARoSecondary			    				= #04ebff								// ArbeSecondary

/// ─── AutoX ───
	// 	AxPrimary								= #2253F0								// AutoXPrimary
	// 	AxPrimaryLight							= #0050F9								// AutoXPrimaryLight
AxSecondary									= #75ebc0								// AutoXSecondary

/// ─── EEG ───
	// EEGSkyBlue30								= #01EBF9								// EEGSkyBlue30
	// EEGSkyBlue40								= #00E7FD								// EEGSkyBlue40
	// EEGFucsia40								= #FF00B1								// EEGFucsia40
	// EEGFucsia50								= #FE0CB6								// EEGFucsia50

/// ─── Bright Line ───
	// 	BrLiYel10								= #FBFD73								// BrightLineBackground Yellow Light
BrLiYel20									= #FFFD52								// BrightLineBackground Yellow Light
	// 	BrLiYel30								= #FDF43C								// BrightLineBackground Yellow High
	// 	BrLiYel40								= #FEF301								// BrightLineBackground Yellow Nit
	// 	BrLiYel50								= #FFDB00								// BrightLineBackground Yellow Base

/// ─── TradingView ───
	// 	TVLightMenta50							= #00ffd5								// TradingViewMenta
TVLightGreen50						    	= #33ffac								// TradingViewGreenNit
	// 	TVBlue50								= #0034c5								// TradingViewBlue
	// 	TVLightYellow50							= #eedd45								// TradingViewYellow
TVNitRed40						    		= #e91e63								// TradingViewRedLight
	// 	TVLightBlueSky50						= #12cef8								// TradingViewBlueSky

/// ─── TFlab ───
TFlAsia			    						= #8bbcfc								// Lite TFlabAsia                        
TFlSydney		    						= #F0B884								// Lite TFlabSydney                      
	// 	TFlTokyo								= #0CC1C0								// Lite TFlabTokyo                       
	// 	TFlShanghai								= #ea1616								// Lite TFlabShanghai                    
	// 	TFlEuro									= #BBE8B5								// Lite TFlabEuro                        
	// 	TFlLondon								= #ACBBE8								// Lite TFlabLondon                      
	// 	TFlNewyork								= #C5ACE8								// Lite TFlabNewyork                     
	// 	TFlNYSE									= #87c2d4								// Lite TFlabNYSE                        

/// ─── Ultr ───
	// UltrBlueSky10								= #59F2E9								// UltrBlueSky10
	// UltrBlueSky20								= #39F0EA								// UltrBlueSky20
	// UltrMenta10									= #E0F9EF								// UltrMenta10
	// UltrMenta20									= #80F3EC								// UtlrMenta20
	// UltrMenta30									= #7FFFD4								// UltrMenta30
	// UltrMenta40									= #73FFCA								// UltrMenta40
	// UltrMenta50									= #9CFFD7								// UtlrMenta50
	// UltrMenta60									= #4fffc0								// UtlrMenta60
	// UltrRose20									= #ffa3e3								// UltrRose
	// UltrFucsia30									= #ff6fd3								// UltrFucsia
	// UltrLyla										= #7E57C2								// UltrLyla
	// UltrLightGray								= #787B86								// UltrLightGray
	// UltrRedNit									= #de0011								// UltrRedNit
	// UltrRed										= #db004b								// UltrRed
	// UltrBlue										= #003bde								// UltrBlue
	// UltrYellow									= #f4de1a								// UltrYellow
	// UltrSkyBlue									= #12cef8								// UltrSkyBlue
	// UltrOrange									= #ff5a00								// UltrOrange

/// ─── Allen ───
AllenSky20									= #80F3EC								// AllenSky20

AllenMint10									= #E0F9EF								// AllenMint10
AllenMint20									= #9CFFD7								// AllenMint20
AllenMint30									= #7FFFD4								// AllenMint30
AllenMint40									= #73FFCA								// AllenMint40
AllenMint50									= #4fffc0								// AllenMint50
AllenMint60									= #33ffac								// AllenMint60

/////////////////

/// ─── Adx Trend colors
colAdxTrendPlus		= color.new(TVLightGreen50,		0)
colAdxTrendP		= color.new(TVLightGreen50,		70)
colAdxTrendMinus	= color.new(AmeTrGrayNickel,	0)
colAdxTrendM		= color.new(AmeTrGrayNickel,	70)
colAdxTrendRange	= color.new(ARoPrimary,			60)

/// ─── Lines colors
colAdxLinePlus		= color.new(AllenMint50,		0)
colAdxLineP			= color.new(AllenMint50,		80)
colAdxLineM			= color.new(AmeTrGrayNickel,	80)
colAdxLineMinus		= color.new(AmeTrGrayNickel,	0)
colAdxRange			= color.new(AllenMint10,		40)

/// ─── Areas colors
colAdxAreaHighP		= color.new(TVLightGreen50,		90)
colAdxAreaHigh		= color.new(TVLightGreen50,		70)
colAdxAreaLow		= color.new(AmeTrGrayNickel,	70)
colAdxAreaLowM		= color.new(AmeTrGrayNickel,	90)
colAdxAreaRange		= color.new(ARoPrimary,			85)

/// ─── Trend
colAdxRibbon		= color.new(AmeTrGrayNickel,	80)
colAdxRibbonBurn	= color.new(ARoPrimary,			90)
colAdxRibbonL		= color.new(AllenMint10,		98)

/// ────────────
/// ─── +Di- ───
/// ─── Variables

sigLength		= input.int		(14, 'ADX Smoothing')
diLength		= input.int		(11, 'DI Length')
levelRange		= input.int		(15, 'Level Range')
levelTrend		= input.int		(30, 'Level Trend')

/// ────────────
/// ─── +Di- ───
/// ─── Functions

functDirMov(_len) =>
	_up				=  ta.change(high)
	_down				= -ta.change(low)
	_plusDM			= na(_up)	? na : _up		> _down and _up		> 0 ? _up	: 0
	_minusDM			= na(_down)	? na : _down	> _up   and _down	> 0 ? _down	: 0
	_trueRange		= ta.rma(ta.tr, _len)
	_plus				= fixnan(100 * ta.rma(_plusDM,	_len) / _trueRange)
	_minus			= fixnan(100 * ta.rma(_minusDM,	_len) / _trueRange)
	[_plus, _minus]

functDirSig(_diLen, _sigLen) =>
	[_plus, _minus]	= functDirMov(_diLen)
	_sum				= _plus + _minus
	_sig				= 100 * ta.rma(math.abs(_plus - _minus) / (_sum == 0 ? 1 : _sum), _sigLen)
	[_sig]

/// ────────────
/// ─── +Di- ───
/// ─── Maths ──

[sig]					= functDirSig   (diLength, sigLength)
[diPlus, _]				= functDirMov(diLength)
[_, diMinus]			= functDirMov(diLength)

bool signal				= diPlus > diMinus
color colorLineCrOver	= signal ? colAdxLinePlus	: colAdxLineMinus
color colorLineCross	= signal ? colAdxLineP		: colAdxLineM

hlRange		= sig		<=	levelRange

diUp		= diPlus	>=	diMinus
diUpUp		= diPlus	>=	levelTrend

diDn		= diMinus	>	diPlus
diDnDn		= diMinus	>	levelTrend

crossDi		= ta.cross		(diPlus, diMinus)
sigUp		= sig		>	sig[1]
sigDir		= sig		>	sig[1] and diUp and not hlRange ?  1 :
			  sig		>	sig[1] and diDn and not hlRange ? -1 : 0

/// ────────────
/// ─── +Di- ───
/// ─── Rules ──

entryLong		= not hlRange and diUp and sigUp and not diUp[1] or
				  not hlRange and diUp and sigUp and sig > levelRange and hlRange[1]
entryShort		= not hlRange and diDn and sigUp and not diDn[1] or
				  not hlRange and diDn and sigUp and sig > levelRange and hlRange[1]
entryLongStr	= not hlRange and diUp and sigUp and diUpUp
entryShortSt	= not hlRange and diDn and sigUp and diDnDn
exitLong		= crossDi and diUp[1] or hlRange and not hlRange[1]
exitShort		= crossDi and diDn[1] or hlRange and not hlRange[1]

/// ─── Lines ──
ruleSig			= hlRange								? colAdxTrendRange	:
				  sigUp	and diUp						? colAdxTrendPlus	:
				  not sigUp	and diUp					? colAdxTrendP		:
				  sigUp	and diDn						? colAdxTrendMinus	:
				  not sigUp	and diDn					? colAdxTrendM		: na

/// ─── Areas ──
fillAdx			= hlRange								? colAdxAreaRange	:
				  not hlRange	and diUp and diUpUp		? colAdxAreaHigh	:
				  not hlRange	and diUp and not diUpUp	? colAdxAreaHighP	:
				  not hlRange	and diDn and diDnDn		? colAdxAreaLowM	:
				  not hlRange	and diDn and not diDnDn	? colAdxAreaLow		: na

/// ────────────
/// ─── +Di- ───
/// ─── Display

/// ─── Plot ───
plot(sig,					title = 'ADX',			color = ruleSig,				linewidth = 7)

pDiPlus = plot(diPlus,		title = '+DI',			color = colorLineCrOver, 		linewidth = 2)   
pDiMinus = plot(diMinus,	title = '-DI',			color = colorLineCross)

fill(pDiPlus, pDiMinus,		title = 'Fill ADX ',	color = fillAdx)

plot(crossDi ? diPlus : na,	title = 'Cross Di',		color = AmeTrGrayNickel,		linewidth = 3,	style = plot.style_circles)
trend1 = hline(levelRange,	title = 'Level Range',	color = colAdxRange,			linewidth = 1,	linestyle = hline.style_dotted)
trend2 = hline(levelTrend,	title = 'Level Trend',	color = colAdxRange,			linewidth = 1,	linestyle = hline.style_dotted)

trend3 = hline(20,			display = display.none,	color = colAdxRibbonL,			linewidth = 1,	linestyle = hline.style_dotted)
trend4 = hline(25,			display = display.none,	color = colAdxRibbonL,			linewidth = 1,	linestyle = hline.style_dotted)
fill(trend3, trend4,		editable = false,		color = colAdxRibbon)
fill(trend1, trend2,		editable = false,		color = colAdxRibbonBurn)

/// ─── Bar ───
// barcolor(i_barColOn ? ruleSig : na)
